#!/usr/bin/env python3
"""
Is the dashboard STALE — does it predate the state it is supposed to show?

WHY THIS EXISTS
---------------
The candidate, 2026-08-03: *"If the daily search ran just after 11am, why did the coordinator not update
the dashboard? Especially since my conversations should have caused it to update. It pushed items
to drafts, but not the dashboard, why?"*

**Because the coordinator had no dashboard step at all.** `generate_dashboard.py` appeared in
`the `jobsearch:daily-run` skill` and `the `jobsearch:weekly-review` skill` — and **zero times** in
`.claude/skills/coordinator/SKILL.md`.

That is the worst possible place for the gap, because the coordinator is the session the candidate actually
works in, and CLAUDE.md's own rule says **"the candidate reads the full text off the dashboard, not the
transcript."** So the one session whose entire output the candidate consumes visually was the one
session that never published. Measured that morning: `drafts.md` was rewritten at 10:58, 11:02,
11:08, 11:13 and 11:14, while `dashboard.html` sat untouched since 10:51 — five rounds of drafting
the candidate could not see.

**Why a script and not a line in the prompt.** The prompts already carried the step and it still
went missing, because the step lived in the runs and the writing happened in the session. A rule
that depends on the right prompt being loaded fails exactly when a different prompt is loaded.
This compares mtimes and does not care who was supposed to remember.

    ⚠️ mtime, not content. If a source is newer than the dashboard, the dashboard cannot be
    showing it. The converse is not proven — a fresh dashboard may still be wrong for other
    reasons, which is why the standing habit is to GREP THE OUTPUT after generating.

## ⭐ THE PUBLISHED VIEW IS A SECOND FRESHNESS DIMENSION (dev #133 / public #22)

Generating the dashboard is not delivering it: the candidate reads a PUBLISHED artifact, and the
publish happens through the Artifact tool — a platform tool only a session can invoke, never a
script. When two sessions race on the same artifact URL the platform refuses the second publish
with a version conflict, and the losing session used to drop it SILENTLY: the repository moved,
the published view did not, and nothing anywhere said so.

No script of ours can republish (only a session holds the Artifact tool), so prevention cannot
ship as code. What ships as code is the guarantee that a dropped publish CANNOT STAY QUIET past
the next check: after a successful publish the session stamps what it published
(`--stamp-published`, a content hash in `.git/` — never committed, like the run lock), and every
later run compares the generated bytes against that stamp. Bytes that differ mean the published
view is behind the repository — dropped publish, forgotten publish, or forgotten stamp, it does
not matter which: **every failure mode converges on the same loud answer, "republish", and
republishing to the same URL is idempotent and cheap.** A false alarm costs one republish; the
old failure cost an unbounded window of the candidate reading a stale dashboard as current. The
asymmetry is the design.

Usage:
    python3 scripts/check_dashboard_fresh.py                    # exit 1 if stale OR publish-behind
    python3 scripts/check_dashboard_fresh.py --fix              # regenerate, then re-check
    python3 scripts/check_dashboard_fresh.py --stamp-published  # AFTER a successful Artifact publish
    python3 scripts/check_dashboard_fresh.py --publish-state    # just the publish dimension

Python 3.9+. Standard library only.
"""

import argparse
import datetime
import hashlib
import json
import os
import subprocess
import sys
import time

import os, sys as _sys
_sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import profile_root as _profile_root
ENGINE_SCRIPTS = os.path.dirname(os.path.realpath(__file__))

ROOT = _profile_root()
DASH = os.path.join(ROOT, "dashboard.html")
ARTIFACT = os.path.join(ROOT, "dashboard_artifact.html")

# Everything the dashboard renders. If one of these moved, the dashboard is behind it.
# (focus.md left this list with dev #93 — the generator no longer reads it; asks.jsonl and
# commitments.jsonl are the stores that replaced it. messages.jsonl joined too: channel
# touch derivation reads it, so a new outbound message can change Your Move.)
SOURCES = [
    "drafts.md", "cover_letters.md", "network.md",
    "data/opportunities.jsonl", "data/companies.jsonl", "data/channels.jsonl",
    "data/messages.jsonl", "data/asks.jsonl", "data/commitments.jsonl",
]


def mtime(p):
    return os.path.getmtime(p) if os.path.exists(p) else 0


# ---- the publish stamp (dev #133 / public #22) ----------------------------------------------

def stamp_path():
    """Inside .git so it is never committed (the run-lock precedent); the profile root itself
    if this profile somehow has no .git — still functional, just visible."""
    d = os.path.join(ROOT, ".git")
    return os.path.join(d if os.path.isdir(d) else ROOT, "last_publish.json")


def artifact_sha():
    try:
        with open(ARTIFACT, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()
    except OSError:
        return None


def read_stamp():
    try:
        with open(stamp_path(), encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def write_stamp():
    """Record what was just published. Refuses when there is nothing to have published."""
    sha = artifact_sha()
    if sha is None:
        print("⛔ REFUSED — %s does not exist, so nothing can have been published."
              % os.path.basename(ARTIFACT))
        print("  Generate first (generate_dashboard.py), publish with the Artifact tool,")
        print("  THEN stamp. Stamping records a publish; it never substitutes for one.")
        return 1
    doc = {"sha256": sha,
           "stamped_at": datetime.datetime.now(datetime.timezone.utc)
                                          .strftime("%Y-%m-%dT%H:%M:%SZ"),
           "_why": "written after a successful Artifact publish (dev #133 / public #22); "
                   "check_dashboard_fresh.py compares the generated bytes against this"}
    with open(stamp_path(), "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=1)
    print("PUBLISH STAMPED — %s… at %s" % (sha[:12], doc["stamped_at"]))
    return 0


def publish_state():
    """('current'|'behind'|'unstamped'|'no-artifact', detail lines).

    'behind' and 'unstamped' both mean the same action: publish, then stamp. They are named
    apart so the report can say WHY — a hash mismatch is a publish that was dropped or never
    attempted since the last regenerate; a missing stamp is a publish nobody ever recorded."""
    sha = artifact_sha()
    if sha is None:
        return "no-artifact", ["no generated artifact yet — the freshness check above is the "
                               "one that gates here"]
    st = read_stamp()
    if not st or not st.get("sha256"):
        # A profile that has NEVER published (no stamp, and no url file — the file the first
        # publish creates) gets an informational pass, not a red it can never clear: the
        # Artifact tool may be legitimately unavailable on this install, and "a gate a user
        # cannot satisfy is not a gate" (coordinator.py #1). The first publish + stamp arms it.
        if not os.path.exists(os.path.join(ROOT, "dashboard_artifact_url.txt")):
            return "never-published", [
                "no publish stamp and no dashboard_artifact_url.txt — this profile has never "
                "published; nothing to compare. The first publish + --stamp-published arms "
                "this check."]
        return "unstamped", [
            "the generated artifact exists but NO publish was ever stamped.",
            "If it was published, the stamp was skipped — the record of delivery is missing",
            "either way. Publish with the Artifact tool (dashboard_artifact_url.txt as `url`),",
            "then: %s --stamp-published" % os.path.basename(__file__)]
    if st["sha256"] != sha:
        return "behind", [
            "the generated artifact DIFFERS from what was last published (stamped %s)."
            % (st.get("stamped_at") or "?"),
            "A publish was dropped (version conflict), skipped, or never stamped — all three",
            "converge on the same fix: publish dashboard_artifact.html with the Artifact tool,",
            "passing dashboard_artifact_url.txt as `url` (on a conflict: regenerate, publish",
            "again — NEVER force), then: %s --stamp-published" % os.path.basename(__file__)]
    return "current", ["published view matches the generated bytes (stamped %s)"
                       % (st.get("stamped_at") or "?")]


def stale():
    """[(source, how_many_seconds_newer)] — empty means the dashboard is current."""
    d = min(mtime(DASH), mtime(ARTIFACT))
    if not d:
        return [(s, 0) for s in SOURCES if os.path.exists(os.path.join(ROOT, s))]
    out = []
    for s in SOURCES:
        m = mtime(os.path.join(ROOT, s))
        if m > d:
            out.append((s, int(m - d)))
    return out


def main():
    ap = argparse.ArgumentParser(description="Is the dashboard behind its sources?")
    ap.add_argument("--fix", action="store_true", help="Regenerate, then re-check.")
    ap.add_argument("--stamp-published", action="store_true",
                    help="Record that dashboard_artifact.html was JUST published with the "
                         "Artifact tool. Run it right after every successful publish (dev #133).")
    ap.add_argument("--publish-state", action="store_true",
                    help="Only the publish dimension: is the PUBLISHED view behind the "
                         "generated bytes? Exit 1 if it provably is.")
    args = ap.parse_args()

    if args.stamp_published:
        return write_stamp()

    if args.publish_state:
        state, lines = publish_state()
        if state in ("behind", "unstamped"):
            print("⚠️  PUBLISHED VIEW BEHIND THE REPOSITORY — a publish was dropped or missed.")
            print("=" * 72)
            for l in lines:
                print("  " + l)
            return 1
        print("PUBLISH %s — %s" % (state.upper().replace("-", " "), lines[0]))
        return 0

    bad = stale()
    if args.fix and bad:
        print("Regenerating (%d source(s) newer)..." % len(bad))
        r = subprocess.run([sys.executable, os.path.join(ENGINE_SCRIPTS, "generate_dashboard.py")],
                           capture_output=True, text=True)
        print("  " + (r.stdout.strip().splitlines() or ["?"])[-1])
        if r.returncode:
            print("  !! generate_dashboard.py failed:\n" + r.stderr.strip()[:400])
            return 1
        bad = stale()

    state, plines = publish_state()

    if not bad:
        print("DASHBOARD CURRENT — no source is newer than the generated files.")
        print("  (Freshness is not correctness: still GREP THE OUTPUT for what you added.)")
        if args.fix:
            # --fix is always followed by the publish step in the run prompts, so a pending
            # publish here is the expected NEXT STEP, not a defect — say it, don't gate on it.
            if state in ("behind", "unstamped"):
                print("  NEXT: publish dashboard_artifact.html with the Artifact tool, then")
                print("        %s --stamp-published" % os.path.basename(__file__))
            return 0
        if state in ("behind", "unstamped"):
            print("\n⚠️  BUT THE PUBLISHED VIEW IS BEHIND — %s" % plines[0])
            for l in plines[1:]:
                print("  " + l)
            return 1
        print("  publish: %s" % plines[0])
        return 0

    print("⚠️  DASHBOARD IS STALE — %d source(s) are newer than what was generated." % len(bad))
    print("=" * 72)
    for s, secs in sorted(bad, key=lambda x: -x[1]):
        mins = secs // 60
        print("  %-32s newer by %s" % (s, "%d min" % mins if mins else "%d sec" % secs))
    print("\n  the candidate reads the full text of drafts and letters OFF THE DASHBOARD, not the")
    print("  transcript. A stale dashboard means work the candidate cannot see — on 2026-08-03 that was")
    print("  five rounds of outreach drafting between 10:58 and 11:14.")
    print("\n  Fix:  python3 scripts/check_dashboard_fresh.py --fix")
    print("  Then publish with the Artifact tool, passing dashboard_artifact_url.txt as `url`,")
    print("  and stamp the publish:  check_dashboard_fresh.py --stamp-published  (dev #133)")
    return 1


if __name__ == "__main__":
    sys.exit(main())
