#!/usr/bin/env python3
"""Install ~/.claude/jobsearch/run — a stable launcher for every engine script.

⭐ WHY A LAUNCHER AND NOT A SHELL VARIABLE (2026-08-05).
`${CLAUDE_PLUGIN_ROOT}` is unset inside a Bash tool call, so the skills first resolved the engine
per command:  ENGINE=$(cat ~/.claude/jobsearch/engine_root); python3 "$ENGINE/scripts/x.py"

That works, and it still fails the thing that matters. A fresh-session run proved it: the form is
a COMPOUND command with a QUOTED path, and a permission allowlist cannot match either — so every
script call stopped for approval. **An unattended run that stops for a prompt is a run that does
not happen**, which is the exact failure the allowlist exists to prevent.

A launcher at a fixed path makes each call a single unquoted command with a stable prefix:

    ~/.claude/jobsearch/run validate_data.py
    ~/.claude/jobsearch/run record.py set acme-cto stage screening

One allowlist entry covers all of them, and the engine can move without touching a single skill.
"""
import json
import os
import stat
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import engine_root

HOME_DIR = os.path.join(os.path.expanduser("~"), ".claude", "jobsearch")
LAUNCHER = os.path.join(HOME_DIR, "run")

TEMPLATE = """#!/bin/sh
# GENERATED by scripts/install_launcher.py — do not edit; re-run that script instead.
#
# Runs an engine script by BARE NAME, so callers need no path and no shell variable:
#     ~/.claude/jobsearch/run validate_data.py --flag
#
# The engine location is read from engine_root at call time, so moving or reinstalling the
# plugin needs no change here and no change in any skill.
# ⭐⭐ THE POINTER CANNOT BE TRUSTED, SO IT IS VALIDATED HERE — AT THE POINT OF USE.
#
# The desktop app materialises the plugin PER SESSION under
# .../local-agent-mode-sessions/<id>/.../rpm/plugin_<id>, and any script run from that copy used
# to record it as the durable pointer. It works while the session lives; afterwards EVERY
# scheduled run fails at its first script call, hours later and unattended.
#
# _root.py now refuses to write such a path — but that only helps once the FIXED copy is the one
# running, and an older session copy keeps poisoning the pointer until the app restarts. Guarding
# the write is therefore necessary and NOT sufficient. This launcher is a stable file that every
# run goes through, so validating here works no matter which copy did the writing.
ENGINE_FILE="$HOME/.claude/jobsearch/engine_root"
ENGINE=""
if [ -f "$ENGINE_FILE" ]; then
  ENGINE=$(cat "$ENGINE_FILE")
fi

CACHE="$HOME/.claude/plugins/cache/careers-plugins/jobsearch"

# Reject a session-scoped pointer, and one naming a directory that no longer exists.
case "$ENGINE" in
  */local-agent-mode-sessions/*|*/rpm/plugin_*) ENGINE="" ;;
esac
if [ -n "$ENGINE" ] && [ ! -d "$ENGINE/scripts" ]; then
  ENGINE=""
fi

# ⭐⭐ A POINTER INSIDE THE INSTALL CACHE IS NOT AUTHORITATIVE — THE NEWEST INSTALL IS.
#
# The cache KEEPS every version ever installed. So once the pointer names a specific version
# directory, that directory goes on existing forever, the "directory is gone" check above never
# fires, and THE ENGINE FREEZES AT THAT VERSION: every later release installs correctly and is
# then silently never used. Nothing errors. Runs keep succeeding against old code, which is the
# worst shape a failure can take here.
#
# This stayed hidden while the pointer named a developer's working tree, because a working tree
# always tracks itself. It surfaced the moment the pointer was aimed at the marketplace copy.
#
# A pointer OUTSIDE the cache is left alone: that is someone deliberately running against a
# checkout, and taking that away would remove the only way to test an unreleased change.
case "$ENGINE" in
  "$CACHE"/*) ENGINE="" ;;
esac

# Resolve to the newest INSTALLED version, which is stable across sessions.
if [ -z "$ENGINE" ]; then
  if [ -d "$CACHE" ]; then
    NEWEST=$(ls -1 "$CACHE" 2>/dev/null | grep -E '^[0-9]+\\.[0-9]+\\.[0-9]+$' \\
             | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)
    if [ -n "$NEWEST" ] && [ -d "$CACHE/$NEWEST/scripts" ]; then
      ENGINE="$CACHE/$NEWEST"
      # Repair it for every other reader, and only when it actually moved — a run must not
      # rewrite this file on every call. Best-effort: a read-only HOME must not break the run.
      if [ "$(cat "$ENGINE_FILE" 2>/dev/null)" != "$ENGINE" ]; then
        printf '%s' "$ENGINE" > "$ENGINE_FILE" 2>/dev/null || true
      fi
    fi
  fi
fi

if [ -z "$ENGINE" ]; then
  echo "No usable engine. $ENGINE_FILE is missing, names a directory that is gone, or points" >&2
  echo "inside a per-session plugin copy, and no installed version was found under" >&2
  echo "\\$HOME/.claude/plugins/cache/careers-plugins/jobsearch." >&2
  echo "Reinstall the plugin, or run install_launcher.py from a checkout." >&2
  exit 2
fi
if [ -z "$1" ]; then
  echo "usage: run <script.py> [args...]" >&2
  exit 2
fi
SCRIPT="$ENGINE/scripts/$1"
shift
if [ ! -f "$SCRIPT" ]; then
  echo "No such engine script: $SCRIPT" >&2
  exit 2
fi
case "$SCRIPT" in
  *.sh) exec /bin/sh "$SCRIPT" "$@" ;;
  *)    exec python3 "$SCRIPT" "$@" ;;
esac
"""


def _install_identity():
    """(marketplace, plugin) this engine is installed under — DERIVED, never assumed.

    The generated launcher's cache fallback used to hardcode `careers-plugins/jobsearch`, so a
    fork registered under any other marketplace name got a launcher whose fallback pointed at a
    cache directory that would never exist: the pointer was the only leg it had, and the first
    stale pointer killed every run. Two derivations, in order:

    1. Installed from the cache: the engine path itself is
       ~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/ — read the two segments.
    2. Installed from a checkout: <repo>/plugins/<plugin>/ — the plugin name is the directory,
       and the repo's own catalog (.claude-plugin/marketplace.json `name`) names the
       registration. Falls back to today's names, which keeps every existing install identical.
    """
    eng = os.path.abspath(engine_root())
    cache_root = os.path.join(os.path.expanduser("~"), ".claude", "plugins", "cache")
    try:
        rel = os.path.relpath(eng, cache_root)
    except ValueError:  # Windows: paths on different drives
        rel = os.pardir
    if not rel.startswith(os.pardir):
        parts = rel.split(os.sep)  # <marketplace>/<plugin>/<version>/...
        if len(parts) >= 2:
            return parts[0], parts[1]
    plugin = os.path.basename(eng.rstrip(os.sep)) or "jobsearch"
    catalog = os.path.join(os.path.dirname(os.path.dirname(eng)),
                           ".claude-plugin", "marketplace.json")
    try:
        with open(catalog, encoding="utf-8") as fh:
            name = (json.load(fh).get("name") or "").strip()
    except (OSError, ValueError):
        name = ""
    return (name or "careers-plugins"), plugin


def install():
    os.makedirs(HOME_DIR, exist_ok=True)
    # TEMPLATE carries the default identity so it stays testable as-is; a non-default
    # marketplace or plugin name is substituted at install time (it appears in the CACHE
    # variable and in the no-engine error message — both must move together).
    marketplace, plugin = _install_identity()
    body = TEMPLATE
    if (marketplace, plugin) != ("careers-plugins", "jobsearch"):
        body = body.replace("careers-plugins/jobsearch", "%s/%s" % (marketplace, plugin))
    with open(LAUNCHER, "w", encoding="utf-8") as fh:
        fh.write(body)
    os.chmod(LAUNCHER, os.stat(LAUNCHER).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    # Ensure the pointer the launcher reads actually exists.
    ptr = os.path.join(HOME_DIR, "engine_root")
    with open(ptr, "w", encoding="utf-8") as fh:
        fh.write(engine_root())
    return LAUNCHER


if __name__ == "__main__":
    print("Installed %s" % install())
    print("Engine    %s" % engine_root())
    print()
    print("Allowlist this one entry to keep unattended runs from prompting:")
    print('    Bash(~/.claude/jobsearch/run:*)')
